source "https://rubygems.org"

gem "rails", "~> 8.1.2"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "dartsass-rails"
gem "bootstrap", "~> 5.3"
gem "importmap-rails"
gem "propshaft", "~> 1.3"
# gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data"
gem "sidekiq"
gem "ros-apartment", "~> 3.4", require: "apartment"

group :development do
  gem "listen", "~> 3.9"
  gem "web-console"
end

