source "https://rubygems.org"

gem "rails", "~> 8.1.2"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "dartsass-rails"
gem "bootstrap", "~> 5.3"
gem "importmap-rails"
gem "propshaft", "~> 1.3"
# gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data"
gem "sidekiq"
gem "ros-apartment", "~> 3.4", require: "apartment"

group :development do
  gem "listen", "~> 3.9"
  gem "web-console"
  gem "rubocop", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rubocop-rspec", require: false
  gem "reek", require: false
end

group :development, :test do
  gem "rspec-rails", "~> 8.0"
  gem "factory_bot_rails"
  gem "faker"
end

